version: "1.8"
services:
  db:
    image: mongo:4.4.4
    restart: always
    container_name: db_container
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    container_name: web_container
    ports:
      - "80:80"
      
      