version: '3'

services:
  app:
    container_name: node_app
    restart: always
    build: .
    ports:
      - '3000:3000'
  mongo:
    container_name: mongo_for_node_app
    image: mongo
    ports:
      - '27017:27017'
